export const ADD_ENTRETIEN = 'ADD_ENTRETIEN';
export const GET_ENTRETIEN = 'GET_ENTRETIEN';
export const GET_ENTRETIENS = 'GET_ENTRETIENS';
export const EDIT_ENTRETIEN = 'EDIT_ENTRETIEN';
export const DELETE_ENTRETIEN = 'DELETE_ENTRETIEN';
export const ERROR_ENTRETIEN = 'ERROR_ENTRETIEN';

