export const ADD_FOURNISSEUR = 'ADD_FOURNISSEUR';
export const GET_FOURNISSEUR = 'GET_FOURNISSEUR';
export const GET_FOURNISSEURS = 'GET_FOURNISSEURS';
export const EDIT_FOURNISSEUR = 'EDIT_FOURNISSEUR';
export const DELETE_FOURNISSEUR = 'DELETE_FOURNISSEUR';
export const ERROR_FOURNISSEUR = 'ERROR_FOURNISSEUR';