server:
  port: 9191

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: app
          uri: lb://app
          predicates:
            - Path=/app/**
        - id: association
          uri: lb://association
          predicates:
            - Path=/Association/**
        - id: event
          uri: lb://event
          predicates:
            - Path=/event/**
        - id: entretien
          uri: lb://entretien
          predicates:
            - Path=/entretien/**

