server:
  port: 9191

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: association
          uri: lb://association
          predicates:
            - Path=/Association/**
        - id: event
          uri: lb://event
          predicates:
            - Path=/event/**
         
  main:
        allow-bean-definition-overriding: true
  security:
    ignored=/**:
    enable-csrf: false